TRCS-107: CEPH S3 Tests
rabataio/s3-ceph-tests pull request #1
Opened 2023-11-13 20:52 UTC by iowanobos

2024-01-21 23:06 UTC, khasanovbi requested changes

2024-01-21 23:06 UTC, khasanovbi commented on tox.ini
>    S3_USE_SIGV4
Этот env прокидывается снаружи?

2024-01-21 23:06 UTC, khasanovbi commented on selection.txt
> +s3tests_boto3/functional/test_s3.py::test_get_object_torrent
torrent у нас не поддержаны

2024-01-21 23:06 UTC, khasanovbi commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_list_delimiter_basic
листинг бакетов должен работать

2024-01-21 23:06 UTC, khasanovbi commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_list_empty
обговаривали что надо запускать тесты и из boto2

2024-01-21 23:06 UTC, khasanovbi commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_list_unordered
листинги должны работать

2024-01-21 23:06 UTC, khasanovbi commented on .github/workflows/s3_tests.yml
> +      - v*
Думаю теги тут не будем делать, как и запуск при пушах в мастер.

2024-01-21 23:06 UTC, khasanovbi commented on s3tests.conf
> +host = 127.0.0.1
Если эти параметры не используются в тесте их можно удалить, vstart.sh не вижу вообще в репе

2024-01-21 23:09 UTC, khasanovbi commented
Написал как вижу деплой через github actions в тикете

2024-02-19 10:35 UTC, iowanobos commented on selection.txt
> +s3tests_boto3/functional/test_s3.py::test_get_object_torrent
закоментировал

2024-02-19 10:35 UTC, iowanobos commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_list_delimiter_basic
добавил

2024-02-19 10:35 UTC, iowanobos commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_list_empty
Тесты пока что не проходят, завел на это задачу: https://trello.com/c/ysQGzUuv

2024-02-19 10:35 UTC, iowanobos commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_list_unordered
данный тест помечен как fails_on_aws и сейчас пропускается

2024-02-19 10:35 UTC, iowanobos commented on .github/workflows/s3_tests.yml
> +      - v*
убрал

2024-02-19 10:35 UTC, iowanobos commented on s3tests.conf
> +host = 127.0.0.1
пошлись по параметрам на Звонке, все параметры используются в тестах

2024-02-26 17:10 UTC, khasanovbi commented
PY_COLORS: 1 давай проставим

2024-03-04 09:34 UTC, khasanovbi requested changes

2024-03-04 09:34 UTC, khasanovbi commented on .github/workflows/s3_tests.yml
> +        uses: actions/setup-python@v4
v5

2024-03-04 09:34 UTC, khasanovbi commented on selection.txt
> +#s3tests/functional/test_s3.py::test_logging_toggle # CreateBucket - MalformedXML - The XML you provided was not well formed or did not validate against our published schema
Не обязательно дублировать текст сообщения, MalformedXML и так понятно, сообщение не дает какой-то полезной информации.

2024-03-04 09:34 UTC, khasanovbi commented on .github/workflows/s3_tests.yml
> +    uses: rabataio/s3-ceph-tests/.github/workflows/reusable_s3_tests.yml@feature/TRCS-107
Не надо полный путь указывать, достаточно `./.github/workflows/reusable_s3_tests.yml`

2024-03-04 09:34 UTC, khasanovbi commented on .github/workflows/reusable_s3_tests.yml
> +jobs:
Вообще можно было composite action сделать вместо workflow, посмотри prepare-go

2024-03-04 09:34 UTC, khasanovbi commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_listv2_encoding_basic # Failed - Assert list_objectsv2 prefix
Почему фейлится, что ожидает что на самом деле, что надо проверить.
Это ко всем тестам относится.

2024-03-04 09:34 UTC, khasanovbi commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_object_raw_get_bucket_gone # Failed - put_object - unimplemented header
какой заголовок?

2024-03-04 09:34 UTC, khasanovbi commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_object_raw_get # Failed - put_object - unimplemented header
Давай писать NotImplemented по названию кода ошибки

2024-03-04 09:34 UTC, khasanovbi commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_post_object_anonymous_request # Failed - _get_post_url - expected 204 but got 405
Там где post_object можно везде написать NotImplemented

2024-03-04 09:34 UTC, khasanovbi commented on s3tests.conf
> +host = s3.stage.rabata.io
Давай хост тоже из env передадим, думаю будем и на aws запускать из интереса эти тесты.

2024-03-04 09:34 UTC, khasanovbi commented on selection.txt
> +s3tests_boto3/functional/test_s3.py::test_sse_kms_read_declare # Failed - get_object - client error not raised
Тест раскомменчен, но ошибка есть

2024-03-04 09:34 UTC, khasanovbi commented on .github/workflows/reusable_s3_tests.yml
> +        with:
не надо тут with указывать

2024-03-04 09:35 UTC, khasanovbi commented on .github/workflows/s3_tests.yml
> +name: CEPH S3 Tests
Ceph

2024-03-18 16:12 UTC, iowanobos commented on selection.txt
> +#s3tests/functional/test_s3.py::test_logging_toggle # CreateBucket - MalformedXML - The XML you provided was not well formed or did not validate against our published schema
поправил

2024-03-18 16:12 UTC, iowanobos commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_bucket_listv2_encoding_basic # Failed - Assert list_objectsv2 prefix
Вместо пробела(%20) приходит +
в AWS та же проблема, решили тест подправить

2024-03-18 16:12 UTC, iowanobos commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_object_raw_get_bucket_gone # Failed - put_object - unimplemented header
тест проходит, в других тестах указал где есть нереализованные заголовки

2024-03-18 16:12 UTC, iowanobos commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_object_raw_get # Failed - put_object - unimplemented header
поправил

2024-03-18 16:12 UTC, iowanobos commented on selection.txt
> +#s3tests_boto3/functional/test_s3.py::test_post_object_anonymous_request # Failed - _get_post_url - expected 204 but got 405
поправил

2024-03-18 16:12 UTC, iowanobos commented on selection.txt
> +s3tests_boto3/functional/test_s3.py::test_sse_kms_read_declare # Failed - get_object - client error not raised
поправил, теперь где справа есть хоть какой-то комент тест не будет запускаться

2024-03-18 16:12 UTC, iowanobos commented on s3tests.conf
> +host = s3.stage.rabata.io
Добавь пожалуйста в переменные HOST

2024-03-19 23:01 UTC, khasanovbi requested changes

2024-03-19 23:01 UTC, khasanovbi commented on pytest.ini
> +    sequential
Договорились убрать sequential

2024-03-19 23:01 UTC, khasanovbi commented on s3tests/functional/test_s3_website.py
> -def test_routing_generator():
используй parametrize плз не надо удалять
https://docs.pytest.org/en/4.6.x/deprecations.html#yield-tests
Вместо dict возможно придется сделать namedtuple

2024-03-19 23:01 UTC, khasanovbi commented on .gitignore
> +.tox
добавь плз сюда .env чтобы можно было локально переменные окружения в файлике хранить

2024-03-19 23:01 UTC, khasanovbi commented on .github/workflows/s3_tests_manual.yml
> +  workflow_call:
я тут еще подумал как можно упростить давай сюда перенесем schedule и pull_request
Можно сделать
`environment: ${{ inputs.environment || 'RCS stage' }}`

2024-03-19 23:01 UTC, khasanovbi commented on .github/workflows/s3_tests.yml
> +    - cron: '0 10 * * *'
Давай в 10 часов по Москве перед митом

2024-03-19 23:01 UTC, khasanovbi commented on s3tests_boto3/functional/test_s3.py
> -    assert response2['StartAfter'] == 'bar'
assert 'StartAfter' not in response2

2024-03-19 23:01 UTC, khasanovbi commented on s3tests_boto3/functional/test_s3.py
>  # Breaks DNS with SubdomainCallingFormat
Этот коммент тоже можно удалить с этих тестов, у нас ничего не ломается

2024-03-19 23:01 UTC, khasanovbi commented on s3tests_boto3/functional/test_s3.py
>      for i in range(5):
Добавь тут сохранение в list плз, а ниже когда итерируешься по бакетам надо только бакеты с именами которые тут создал использовать, а не все

2024-03-19 23:01 UTC, khasanovbi commented on tox.ini
> +commands = pytest -n auto -k "not fails_on_aws" --deselect-from-file=deselection.txt
- Если ты явно в deselect прописываешь `# Skipped - fails_on_aws`, тогда, наверное, тут не нужно указывать `"not fails_on_aws"`
- Можно так прописать, чтобы была возможность запускать тесты с select-from через tox `{posargs:--deselect-from-file=deselection.txt}`

2024-03-21 14:50 UTC, iowanobos commented on pytest.ini
> +    sequential
убрано

2024-03-21 14:50 UTC, iowanobos commented on s3tests/functional/test_s3_website.py
> -def test_routing_generator():
вернул и добавил ignore PytestCollectionWarning

2024-03-21 14:50 UTC, iowanobos commented on .gitignore
> +.tox
добавил

2024-03-21 14:50 UTC, iowanobos commented on .github/workflows/s3_tests_manual.yml
> +  workflow_call:
сделал

2024-03-21 14:50 UTC, iowanobos commented on .github/workflows/s3_tests.yml
> +    - cron: '0 10 * * *'
поправил

2024-03-21 14:50 UTC, iowanobos commented on s3tests_boto3/functional/test_s3.py
> -    assert response2['StartAfter'] == 'bar'
поправил

2024-03-21 14:50 UTC, iowanobos commented on s3tests_boto3/functional/test_s3.py
>  # Breaks DNS with SubdomainCallingFormat
удалил

2024-03-21 14:50 UTC, iowanobos commented on s3tests_boto3/functional/test_s3.py
>      for i in range(5):
добавил. тест проходит, убрал из deselection

2024-03-21 14:50 UTC, iowanobos commented on tox.ini
> +commands = pytest -n auto -k "not fails_on_aws" --deselect-from-file=deselection.txt
поправил

2024-03-21 16:02 UTC, khasanovbi requested changes

2024-03-21 16:02 UTC, khasanovbi commented on .github/workflows/s3_tests.yml
> +  workflow_call:
можно убрать

2024-03-21 16:02 UTC, khasanovbi commented on s3tests/functional/test_s3_website.py
> -def test_routing_generator():
Поясни плз для чего PytestCollectionWarning?

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +# UnsupportedAuthorizationType
Давай связанные ошибки в одну схлопнем видно что aws2 сигнатура не заимплеменчена.

```
# UnsupportedAuthorizationType
s3tests/functional/test_headers.py::test_object_create_bad_contentlength_mismatch_below_aws2
s3tests/functional/test_headers.py::test_object_create_bad_authorization_incorrect_aws2
...
```

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +s3tests/functional/test_utils.py::test_generate
А почему тут проскипано?

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +# Failed - Nginx issue
А тут точно с nginx проблема?

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +# UnsupportedAuthorizationType
Нужно схлопнуть в отдельный блок

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +# Skipped
NotImplemented

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +s3tests_boto3/functional/test_utils.py::test_generate
Почему проскипано?

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +# NotImplemented - POST Object
Нужно схлопнуть в отдельный блок

2024-03-21 16:02 UTC, khasanovbi commented on deselection.txt
> +# NotImplemented - PutBucketVersioning
Нужно схлопнуть в отдельный блок

2024-03-21 16:02 UTC, khasanovbi commented on s3tests/functional/test_headers.py
> +@pytest.fixture(autouse=True)
Зачем тут autouse?

2024-03-21 16:02 UTC, khasanovbi commented on s3tests/functional/test_headers.py
> +    _add_custom_headers(headers=dict(Host=targets.main.default.connection.host)) # TODO: delete when MalformedXML will be fixed
Не совсем понятно как связаны совпадение хоста и MalformedXML.

2024-03-21 16:02 UTC, khasanovbi commented on s3tests/functional/test_headers.py
> +    print("ERROR1:", e)
принты надо убрать по коду

2024-03-21 16:02 UTC, khasanovbi commented on s3tests_boto3/functional/test_s3.py
> +    bucket_names = []
Давай тут set() сделаем, ну или вообще можно сделать
`bucket_names = {get_new_bucket_name() for i in range(5)}`

2024-03-21 16:37 UTC, iowanobos commented on s3tests/functional/test_s3_website.py
> -def test_routing_generator():
я убрал тест(случайно закомитил) из-за варнинга, который сейчас игнорю так как он все равно скипается
<img width="1637" alt="Screenshot 2024-03-21 at 17 35 40" src="https://github.com/rabataio/s3-ceph-tests/assets/37349655/dc3f94a0-c63c-4fe9-8a4c-ae1469f13266">

2024-03-21 17:04 UTC, iowanobos commented on .github/workflows/s3_tests.yml
> +  workflow_call:
точно! убрал

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +# UnsupportedAuthorizationType
схлопнул

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +s3tests/functional/test_utils.py::test_generate
убрал

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +# Failed - Nginx issue
Да, на звонке так решили, потому как получаем ответ вида:
```html
<html>
<head>
    <title>400 Bad Request</title>
</head>
<body>
<center>
    <h1>400 Bad Request</h1>
</center>
<hr>
<center>Angie/1.3.1</center>
</body>
</html>
 ```

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +# Skipped
поправил

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +# UnsupportedAuthorizationType
схлопнул

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +s3tests_boto3/functional/test_utils.py::test_generate
убрал

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +# NotImplemented - POST Object
схлопнул

2024-03-21 17:04 UTC, iowanobos commented on deselection.txt
> +# NotImplemented - PutBucketVersioning
схлопнул

2024-03-21 17:04 UTC, iowanobos commented on s3tests/functional/test_headers.py
> +@pytest.fixture(autouse=True)
убрал

2024-03-21 17:04 UTC, iowanobos commented on s3tests/functional/test_headers.py
> +    _add_custom_headers(headers=dict(Host=targets.main.default.connection.host)) # TODO: delete when MalformedXML will be fixed
поправил сообщение

2024-03-21 17:04 UTC, iowanobos commented on s3tests/functional/test_headers.py
> +    print("ERROR1:", e)
убрал

2024-03-21 17:04 UTC, iowanobos commented on s3tests_boto3/functional/test_s3.py
> +    bucket_names = []
сделал

2024-03-23 07:14 UTC, khasanovbi requested changes

2024-03-23 07:14 UTC, khasanovbi commented on .github/workflows/s3_tests.yml
> +        uses: actions/setup-python@v4
Надо вернуть

2024-03-23 07:14 UTC, khasanovbi commented on deselection.txt
> +# Skipped - fails_on_aws
Тут можно Skipped просто оставить, эта логика вообще не s3

2024-03-23 07:14 UTC, khasanovbi commented on s3tests_boto3/functional/test_headers.py
> +    if 'Content-MD5' in headers:
Для чего тут такой if сделан?

2024-03-23 07:14 UTC, khasanovbi commented on s3tests/functional/__init__.py
> -    bucket = connection.create_bucket(name, location=target.conf.api_name, headers=headers)
А зачем location убрал?

2024-03-23 07:14 UTC, khasanovbi commented on deselection.txt
> +s3tests_boto3/functional/test_s3.py::test_object_write_with_chunked_transfer_encoding
Надо проверить, что все нормально

2024-03-23 07:14 UTC, khasanovbi commented on deselection.txt
> +# Failed - missing GetObject metadata
Надо проверить что 4 теста работают

2024-03-23 07:14 UTC, khasanovbi commented on deselection.txt
> +s3tests_boto3/functional/test_s3.py::test_multipart_upload_resend_part
Надо проверить что тест проходит

2024-03-23 07:14 UTC, khasanovbi commented on s3tests/functional/test_s3_website.py
> -def test_routing_generator():
нужно поменять на parametrize с namedtuple как я уже писал и убрать PytestCollectionWarning из игнора

2024-03-25 09:13 UTC, iowanobos commented on .github/workflows/s3_tests.yml
> +        uses: actions/setup-python@v4
вернул

2024-03-25 09:13 UTC, iowanobos commented on s3tests/functional/test_s3_website.py
> -def test_routing_generator():
поправлено

2024-03-25 09:13 UTC, iowanobos commented on deselection.txt
> +# Skipped - fails_on_aws
проставил

2024-03-25 09:13 UTC, iowanobos commented on s3tests_boto3/functional/test_headers.py
> +    if 'Content-MD5' in headers:
там нюанс в проставлении заголовков для определенных тестов в нужный момент, могу метод разделить на два чтобы вызывать before-call и before-send отдельно

2024-03-25 09:13 UTC, iowanobos commented on s3tests/functional/__init__.py
> -    bucket = connection.create_bucket(name, location=target.conf.api_name, headers=headers)
при проставлении тесты не проходят:
request: 
```xml
<CreateBucketConfiguration>
	<LocationConstraint>eu-central-1</LocationConstraint>
</CreateBucketConfiguration>
```
response:
```xml
<Error>
	<Code>MalformedXML</Code>
	<Message>The XML you provided was not well formed or did not validate against our published schema</Message>
	<RequestId>5ADD29DE0E0249CB</RequestId>
</Error>
```

указали тесты как MalformedXML

2024-03-25 09:13 UTC, iowanobos commented on deselection.txt
> +s3tests_boto3/functional/test_s3.py::test_object_write_with_chunked_transfer_encoding
тест проходит, убрал из deselection

2024-03-25 09:13 UTC, iowanobos commented on deselection.txt
> +# Failed - missing GetObject metadata
все проходят кроме s3tests_boto3/functional/test_s3.py::test_object_set_get_unicode_metadata

2024-03-25 09:13 UTC, iowanobos commented on deselection.txt
> +s3tests_boto3/functional/test_s3.py::test_multipart_upload_resend_part
тест не проходит, получаем StreamingError

2024-03-25 10:11 UTC, iowanobos commented on s3tests_boto3/functional/test_headers.py
> +    if 'Content-MD5' in headers:
разделили headers на before-call и before-send

2024-03-25 13:02 UTC, khasanovbi approved these changes

2024-03-25 13:56 UTC, merged